# Generated by Django 3.1.4 on 2020-12-19 11:19

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_in_markdown",
            field=martor.models.MartorField(),
        ),
    ]
