# Generated by Django 3.1.4 on 2021-01-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20201219_1119"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
