# Generated by Django 3.1.4 on 2021-01-05 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_auto_20210103_1224"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blog",
            name="created_on",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
