# Generated by Django 3.1.5 on 2021-01-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_auto_20210105_1158"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["-created_on"]},
        ),
    ]
